### ISSUE TITLE
Query failed to run by returning code of 401.

### ISSUE THREAD

**Issue by hiruthicShaSS** [athul/waka-readme#65]
I just created the workflow but it throws me this error.

```bash
Run anmol098/waka-readme-stats@master
/usr/bin/docker run --name a33c17796a9c327854016a35c2037f9110477_c1259f --label 8a33c1 --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_LOC_CHART -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_SHORT_INFO -e INPUT_LOCALE -e INPUT_COMMIT_BY_ME -e INPUT_IGNORED_REPOS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hiruthicShaSS/hiruthicShaSS":"/github/workspace" 8a33c1:7796a9c327854016a35c2037f9110477
Traceback (most recent call last):
Exception Occurred Query failed to run by returning code of 401. 
  File "/main.py", line 497, in <module>
{
    user_data = run_query(userInfoQuery)  # Execute the query
    viewer {
  File "/main.py", line 156, in run_query
      login
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
      email
Exception: Query failed to run by returning code of 401. 
      id
{
    }
    viewer {
  }
      login

      email
      id
    }
  }
```

**Comment by joe733** [comment]
Hi @hiruthicShaSS, in https://github.com/hiruthicShaSS/hiruthicShaSS/commit/c0d844b15b405cf2fa7b924f5dd3d1eaf971e237 you're using `anmol098/waka-readme-stats@master` instead of `athul/waka-readme@master` at [line 13](https://github.com/hiruthicShaSS/hiruthicShaSS/blob/78f2c78f3a30c3f779748443fe71c2e6c0b60e31/.github/workflows/wakatime.yml#L13).

Feel free to use `athul/waka-readme@master` and let us know if any bugs are sneaking around 😉

**Comment by hiruthicShaSS** [comment]
I am really dumb😥. I am so sorry for disturbing I should've looked carefully. Thanks for the reply too this workflow works like a charm. Nice project buddy👍

**Comment by joe733** [comment]
No problem! happy coding :)
